---
- name: Install docker.io and python3-pip with apt
  hosts: webservers
  become: true
  tasks: 
  - name: install docker.io
    apt:
     force_apt_get: yes
     update_cache: yes
     name: docker.io
     state: present
  
  - name: install python3-pip
    apt:
     name: python3-pip
     state: present
  
  - name: Install docker python module using pip
    pip: 
     name: docker 
     state: present
  
  - name: download and launch a docker web container
    docker_container:
     name: dvwa
     image: cyberxsecurity/dvwa
     state: started
     published_ports: 80:80

  - name: Enable docker service
    systemd:
     name: docker
  - name: Enable docker service
    systemd:
     name: docker
     state: started
     enabled: yes
